CREATE TABLE short_urls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alias VARCHAR(32) NOT NULL,
    original_url VARCHAR(2048) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    access_count BIGINT NOT NULL,
    CONSTRAINT uk_short_urls_alias UNIQUE (alias)
);
